{
 "title": "Window Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Monitoring dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Production Area - Window 1 Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'Production_Window_1' GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Production Area - Window 1 Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'Production_Window_1' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Production Area - Window 2 Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'Production_Window_2' GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Production Area - Window 2 Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'Production_Window_2' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Production Area - Window 3 Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'Production_Window_3' GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Production Area - Window 3 Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'Production_Window_3' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Production Area - Window 4 Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'Production_Window_4' GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Production Area - Window 4 Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'Production_Window_4' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Quality Area - Window 1 Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'QC_Window_1' GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quality Area - Window 1 Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'QC_Window_1' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Quality Area - Window 2 Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'QC_Window_2' GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quality Area - Window 2 Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'QC_Window_2' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Quality Area - Window 3 Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'QC_Window_3' GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quality Area - Window 3 Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'QC_Window_3' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Quality Area - Window 4 Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'QC_Window_4' GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quality Area - Window 4 Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"state\") FROM \"status\" WHERE $timeFilter AND \"location\" = 'QC_Window_4' GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}